import { getDictionary } from "@/lib/get-dictionary";
import { getLocale } from "@/lib/get-locale";
import { DouyinClient } from "@/components/client/douyin-client";
import { Metadata } from "next";

export async function generateMetadata(): Promise<Metadata> {
  const locale = await getLocale();
  const dict = await getDictionary(locale);

  const baseUrl = "https://ssdown.app";
  const canonical = `${baseUrl}/douyin`;

  return {
    title: "Douyin Video Downloader (抖音) — No Watermark | SSDown",
    description:
      "Download Douyin (抖音) videos without watermark for free. Save HD MP4 videos and MP3 audio from any public Douyin post instantly.",
    keywords: [
      "douyin downloader",
      "抖音 downloader",
      "download douyin video",
      "douyin no watermark",
      "douyin video saver",
      "douyin mp4",
      "douyin mp3",
      "抖音视频下载",
      "douyin video download online",
      "save douyin video without watermark",
      "douyin to mp4 converter",
      "douyin to mp3 converter",
      "抖音视频下载器",
      "抖音无水印下载",
      "抖音转mp4",
      "抖音音频提取",
      "douyin hd download",
      "download douyin without login",
      "free douyin video downloader",
      "douyin short video download",
      "v.douyin.com downloader",
      "抖音短视频保存",
    ],
    robots: {
      index: true,
      follow: true,
    },
    openGraph: {
      title: "Douyin Video Downloader (抖音) — No Watermark | SSDown",
      description:
        "Download Douyin (抖音) videos without watermark for free. Save HD MP4 videos and MP3 audio instantly.",
      url: canonical,
      siteName: "SSDown",
      images: [
        {
          url: "https://ssdown.app/ssdown-douyin-og.png",
          width: 1200,
          height: 630,
          alt: "SSDown - Douyin Video Downloader",
        },
      ],
      locale: locale === "kr" ? "ko_KR" : "en_US",
      type: "website",
    },
    twitter: {
      card: "summary_large_image",
      title: "Douyin Video Downloader (抖音) — No Watermark",
      description:
        "Download Douyin videos without watermark. Save MP4 and MP3 instantly.",
      images: ["https://ssdown.app/ssdown-douyin-og.png"],
    },
    alternates: {
      canonical,
    },
  };
}

export default async function DouyinPage() {
  const locale = await getLocale();
  const dict = await getDictionary(locale);

  const faqJsonLd = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: [
      {
        "@type": "Question",
        name: "What is Douyin (抖音)?",
        acceptedAnswer: {
          "@type": "Answer",
          text: "Douyin is the original Chinese version of TikTok, developed by ByteDance. It operates separately from the international TikTok app and is only accessible within China.",
        },
      },
      {
        "@type": "Question",
        name: "Can I download Douyin videos without a watermark?",
        acceptedAnswer: {
          "@type": "Answer",
          text: "Yes. SSDown fetches the original video stream before the watermark overlay is applied, so you get a clean MP4 file without any Douyin branding.",
        },
      },
      {
        "@type": "Question",
        name: "What Douyin URL formats are supported?",
        acceptedAnswer: {
          "@type": "Answer",
          text: "SSDown supports standard Douyin URLs (douyin.com/video/...) as well as short share links (v.douyin.com/...) generated by the Douyin app.",
        },
      },
      {
        "@type": "Question",
        name: "Can I download private Douyin videos?",
        acceptedAnswer: {
          "@type": "Answer",
          text: "No. SSDown can only download publicly available Douyin videos. Private or restricted videos cannot be accessed by third-party tools because they require authenticated access within the Douyin app.",
        },
      },
      {
        "@type": "Question",
        name: "Is downloading Douyin videos legal?",
        acceptedAnswer: {
          "@type": "Answer",
          text: "Downloading publicly available videos for personal, offline viewing is generally acceptable. However, redistributing, re-uploading, or using downloaded content commercially without the creator's permission may violate copyright laws and Douyin's terms of service.",
        },
      },
    ],
  };

  const webAppJsonLd = {
    "@context": "https://schema.org",
    "@type": "WebApplication",
    name: "SSDown Douyin Video Downloader",
    url: "https://ssdown.app/douyin",
    applicationCategory: "MultimediaApplication",
    operatingSystem: "Any",
    offers: { "@type": "Offer", price: "0", priceCurrency: "USD" },
    description:
      "Free online tool to download Douyin (抖音) videos without watermark as MP4 or MP3.",
    featureList: [
      "No watermark",
      "HD quality",
      "MP3 extraction",
      "No login required",
    ],
  };

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(webAppJsonLd) }}
      />
      <DouyinClient dict={dict} />
    </>
  );
}
